<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NotepadX</AssemblyName>
    <RootNamespace>NotepadX</RootNamespace>
    <Product>NotepadX</Product>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
